runtime: nodejs12
env: standard

handlers:
- url: /_next/static
  static_dir: .next/static
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
