name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  lint-test-build-deploy:
    name: Lint, Test, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credential: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint --fix
      
      - name: Build SSR
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
